### ISSUE TITLE
The series2/usart/async_interrupt/ project compile failed when update SDK to v4.0.0

### ISSUE THREAD

**Issue by huangzhixin521** [SiliconLabs/peripheral_examples#109]
Problem description:
![image](https://user-images.githubusercontent.com/95276758/147460030-88009a96-7c15-4412-b34d-0b803e840a26.png)
The series2/usart/async_interrupt/ project compile error:  gecko_sdk\platform\emlib\inc/em_bus.h:307: undefined reference to `CORE_EnterCritical'

Debug:
![image](https://user-images.githubusercontent.com/95276758/147458821-d82ec025-7d4a-4790-8b67-9a3833a2aded.png)
There is no em_core.c file link under "series2/usart/async_interrupt/emlib/" folder.
When add em_core.c file link，the project can compile sucessfully

**Gecko SDK Suite version**
v4.0.0

**Board**
BRD4182A

**Comment by luweiguo511china** [comment]
Yes, the em_core.c missed in the project file.
`  <module id="com.silabs.sdk.exx32.common.emlib">
    <include pattern="emlib/em_cmu.c" />
    <include pattern="emlib/em_emu.c" />
    <include pattern="emlib/em_gpio.c" />
    <include pattern="emlib/em_system.c" />
    <include pattern="emlib/em_usart.c" />
  </module>`

**Comment by silabs-marao** [comment]
The examples are not build tested against v4.0.0. Please note the Requirements here - https://github.com/SiliconLabs/peripheral_examples

**Requirements**

1. Desired Silicon Labs Starter Kit
2. Simplicity Studio 5 or IAR Workbech IDE
3. Gecko SDK Suite 3.2 and 32-bit MCU SDK 6.1.2.0, available via Simplicity Studio
4. This repo, cloned to to C:\SiliconLabs\SimplicityStudio\v5\developer\sdks\gecko_sdk_suite\v#.#\, where #.# is the Gecko SDK suite version number

However, we do plan to switch to SDK v4.0.0 soon. This issue will be fixed when we update all the examples to the newer SDK.
